export default {
  jwtExpiresIn: 15 * 60,
  redisExpiresIn: 15 * 60,
  jwtSecret: process.env.JWT_SECRET!,
  port: Number(process.env.PORT!),
  admin: {
    firstName: process.env.ADMIN_FIRSTNAME!,
    lastName: process.env.ADMIN_LASTNAME!,
    email: process.env.ADMIN_EMAIL!,
    phoneNumber: process.env.ADMIN_PHONENUMBER!,
    address: process.env.ADMIN_ADDRESS!,
    password: process.env.ADMIN_HASHEDPASSWORD!,
    unhashedPassword: process.env.ADMIN_PASSWORD!,
    role: process.env.ADMIN_ROLE!,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  instructor: {
    firstName: process.env.INSTRUCTOR_FIRSTNAME!,
    lastName: process.env.INSTRUCTOR_LASTNAME!,
    email: process.env.INSTRUCTOR_EMAIL!,
    phoneNumber: process.env.INSTRUCTOR_PHONENUMBER!,
    address: process.env.INSTRUCTOR_ADDRESS!,
    password: process.env.INSTRUCTOR_HASHEDPASSWORD!,
    unhashedPassword: process.env.INSTRUCTOR_PASSWORD!,
    role: process.env.INSTRUCTOR_ROLE!,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  student: {
    firstName: process.env.STUDENT_FIRSTNAME!,
    lastName: process.env.STUDENT_LASTNAME!,
    email: process.env.STUDENT_EMAIL!,
    phoneNumber: process.env.STUDENT_PHONENUMBER!,
    address: process.env.STUDENT_ADDRESS!,
    password: process.env.STUDENT_HASHEDPASSWORD!,
    unhashedPassword: process.env.STUDENT_PASSWORD!,
    role: process.env.STUDENT_ROLE!,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};
